title: Pactus blockchain
email: info@pactus.org
decription: Building decentralized future together!
source: website
baseurl: ""
url: "https://pactus.org"
logo: "/assets/images/logos/64_circle.png"

plugins:
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

languages: ["en", "ar", "zh"]

exclude_from_localizations: ["assets", "404.html", "_posts", "blog"]

markdown: kramdown

paginate: 100
paginate_path: blog/page:num/

feed:
  posts_limit: 20

sass:
  style: compressed

latest_version: "0.15.0"
