title: Pactus blockchain
email:
source: website
baseurl: ""
url: "https://www.pactus.org"
logo: "/assets/images/logos/64_circle.png"

plugins:
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

languages: ["en", "ar"]

exclude_from_localizations: ["assets", "404.html", "_posts", "blog"]

markdown: kramdown

paginate: 10
paginate_path: blog/page:num/

feed:
  posts_limit: 20

sass:
  style: compressed
